Spina::Authentication
SpinaCMS/Spina pull request #744
Opened 2021-07-05 16:45 UTC by Bramjetten

Extracted authentication so it's easier to swap it out for something like Devise

2021-07-22 20:08 UTC, simmerz requested changes
I like what's here, but I'd like to see a test against the default auth, and separately a test using the custom `session[:user_id]` module so we don't end up with issues down the line.

2021-07-23 13:08 UTC, Bramjetten commented
So... I've been working on tests for this, but it looks like it's quite hard to test this properly. Changing `config.authentication` and reloading `Spina::ApplicationController` apparently doesn't cut it. Not sure how to tackle this.

2021-07-23 20:36 UTC, Bramjetten commented
Took some effort, but included tests for different auth strategies!

2021-07-24 21:10 UTC, simmerz approved these changes

2021-07-25 07:09 UTC, merged